name: tree-classification
channels:
  - conda-forge
dependencies:
  - keras 
  - dask
  - deepforest
  - geopandas
  - jupyterlab
  - laspy
  - matplotlib
  - seaborn
  - rioxarray
  - scikit-image
  - zarr
  - pip
  - pip:
    - tensorflow